repos:
  - repo: local
    hooks:
      - id: prevent-protected-files-change
        name: Prevent commits that modify protected files
        entry: ./scripts/prevent-protected-files-change.sh
        language: script
        types: [file]
      - id: check-mixin-registration
        name: Checks if every mixin is added to the mixin list
        entry: ./scripts/check-mixin-registration.sh
        language: script
        types: [file]
      - id: check-mixin-smoke-required
        name: Remind to run mixin smoke test if mixins changed
        entry: ./scripts/check-mixin-smoke-required.sh
        language: script
        always_run: true
        pass_filenames: false
